secrets:
  jwtSecret: "480bc3a033673ec1a79f9a84a39f275ac990ad9b23625cd5b8fe1fb5c56499c8"
  openrouterApiKey: "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"
  databaseUrl: "postgresql://neondb_owner:npg_D07tFwKVELcB@ep-dawn-term-aiwovdjs-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
